name: snschat_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:

# Required Plugins
  url_launcher: ^5.0.2
  date_format: ^1.0.6
#  flutter_html_textview: ^0.2.6 # Final decision, html textview causing lot more trouble than version solving
  cached_network_image: ^0.7.0
  flutter_cache_manager: ^0.3.2
  path_provider: ^0.5.0+1 # A Flutter plugin for finding commonly used locations on the filesystem. Supports iOS and Android.
  barcode_scan: ^1.0.0 # A Flutter plugin for scanning 2D barcodes and QR codes as a wrapper using specific iOS mikebuss/MTBBarcodeScanner and Android dm77/barcodescanner library.
  qr_flutter: ^2.0.0+51 # QR.Flutter is a QR code generation and rendering library for Flutter.
  fluttertoast: ^3.0.3
  image_picker: ^0.5.0+9
  pull_to_refresh: ^1.1.6
  contacts_service: ^0.2.4
  permission_handler: ^3.0.0

# State management
  bloc: ^0.11.1
  flutter_bloc: ^0.9.1
  equatable: ^0.2.3

  #Google DB
  firebase_auth: ^0.8.1+4
  google_sign_in: ^4.0.1+1

  # Local DB
  sqflite: ^1.1.3
  jaguar_orm: ^2.2.0
  jaguar_query_sqflite: ^2.2.0

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  jaguar_orm_gen: ^2.2.0
  build_runner: ^0.10.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
# YOU MUST PUT assets: with indentation RIGHT BENEATH THE flutter: key, or else everything won't work
flutter:
  assets:
    - lib/ui/images/
    - lib/ui/icons/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  #fonts:
  #- family: OpenSans
  #  fonts:
  #  - asset: fonts/OpenSans-Bold.ttf
  #    style: bold
  #  - asset: fonts/OpenSans-BoldItalic.ttf
  #    style: bolditalic
  #  - asset: fonts/OpenSans-ExtraBold.ttf
  #    style: extrabold
  #  - asset: fonts/OpenSans-ExtraBoldItalic.ttf
  #    style: extrabolditalic
  #  - asset: fonts/OpenSans-Italic.ttf
  #    style: italic
  #  - asset: fonts/OpenSans-Light.ttf
  #    style: light
  #  - asset: fonts/OpenSans-LightItalic.ttf
  #    style: lightitalic
  #  - asset: fonts/OpenSans-Regular.ttf
  #    style: regular
  #  - asset: fonts/OpenSans-SemiBold.ttf
  #    style: semibold
  #  - asset: fonts/OpenSans-SemiBoldItalic.ttf
  #    style: semibolditalic

  #- family: RobotoMono
  #  fonts:
  #  - asset: fonts/RobotoMono-Regular.ttf
  #  - asset: fonts/RobotoMono-Bold.ttf
  #    weight: 700

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
